### ISSUE TITLE
`pos-tip` uses `x-display-pixel-width`, which isn't defined if Emacs isn't compiled with X support

### ISSUE THREAD

**Issue by ramnes** [meqif/flymake-diagnostic-at-point#1]
Hey there!

I would love to use your small package, that looks neat, but I get the following error whenever I put my cursor on an line highlighted by `flymake`:

```
Error running timer ‘flymake-diagnostic-at-point-maybe-display’: (void-function pop-tip-show)
```

GNU Emacs 26.1, no X, HEAD on your repository as well as `pos-tip`.

**Comment by ramnes** [comment]
So I figured out that `pop-tip-show` might be just a typo, and replaced it by `pos-tip-show`, and now there is another error:

```
Error running timer ‘flymake-diagnostic-at-point-maybe-display’: (void-function x-display-pixel-width)
```

Seems like the problem is on `pos-tip` side now. Isn't `x-display-pixel-width` deprecated? and thus `pos-tip` also?

Maybe you should switch to something a tad more modern like `popup.el`? :relieved:

**Comment by meqif** [comment]
Hi, thanks for the bug report!

As I mentioned in #2, I applied your commit fixing the typo, thanks!

Regarding `x-display-pixel-width`,  its documentation does not say anything about it being deprecated, at least on Emacs HEAD (`GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin17.7.0, NS appkit-1561.60 Version 10.13.6 (Build 17G65)) of 2018-08-13`), so I'm not sure what that is about. 🤔

**Comment by ramnes** [comment]
To be honest a lot of things are moving around on Emacs those days so it's 100% possible that I mixed this up with something else. :smile: 

That being said, I think I have the answer as to why this function is void to me: https://github.com/emacs-mirror/emacs/blob/ddb26f79b20329ada5f5bc6e1742807d029e06c0/lisp/dframe.el#L429

Because yeah, I compile Emacs myself (hello Gentoo), and without X support.

**Comment by meqif** [comment]
I see, that makes sense. Thanks for digging into it.

As a former Gentoo user, it's good to know that it still has users. :)
