### ISSUE TITLE
wishlist: submit a melpa recipe for this package...

### ISSUE THREAD

**Issue by slippycheeze** [meqif/flymake-diagnostic-at-point#3]
G'day.  I see that your package is not available on either elpa or melpa; it would be great if you were willing to publish it to one or the other, since that'd make it much more discoverable as well as more uniform to install.

The [melpa contribution guide](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org) covers the details, but it is generally a very small pull request, simply pointing to your github repo, and the rest happens by magic.

I'm asking this, in part, because having you submit the PR for the recipe to melpa is better than me, but if you don't want to, I'm happy to do that instead.  Unless, of course, you object entirely to the possibility...

**Comment by waymondo** [comment]
I just opened a PR on melpa for this

**Comment by waymondo** [comment]
this is now on MELPA, so this issue is safe to close.
